name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create directory structure
        run: |
          mkdir -p ./build/python
          # Check and copy files from the correct locations
          cp python/main.py ./build/python/
          cp python/pyproject.toml ./build/python/ || echo "pyproject.toml not found, skipping"
          cp generated-icon.png ./build/ || echo "generated-icon not found, skipping"
          cp index.html ./build/ || echo "index.html not found, skipping"
          cp main.js ./build/ || echo "main.js not found, skipping"
          cp style.css ./build/ || echo "style.css not found, skipping"
          
          # List the files in the repository for debugging
          echo "Files in repository:"
          ls -la
          
          # Create placeholder files if they don't exist
          [ -f "./build/python/main.py" ] || echo "print('Hello from Python WASM!')" > ./build/python/main.py
          [ -f "./build/index.html" ] || cp index || echo "<!DOCTYPE html><html><head><title>Python WASM App</title></head><body><h1>Python WASM App</h1></body></html>" > ./build/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
